repos:
  - repo: https://github.com/dycw/pre-commit-hooks
    rev: 0.15.22
    hooks:
      - id: add-hooks
        args:
          - --certificates
          - --ci-gitea
          - --ci-image
          - --ci-image-namespace=qrt
          - --ci-image-registry-host=gitea.qrt
          - --ci-image-registry-password=${{secrets.QRT_GITEA_READ_WRITE_TOKEN}}
          - --ci-image-registry-port=3000
          - --ci-image-registry-username=qrt-bot
          - --ci-image-runs-on=host-linux
          - --ci-pytest-os=ubuntu-latest
          - --ci-pytest-sops-age-key=${{secrets.SOPS_AGE_KEY}}
          - --ci-python-index-password-read=${{secrets.NANODE_PYPI_PASSWORD}}
          - --ci-python-index-password-write=${{secrets.NANODE_PYPI_PASSWORD}}
          - --ci-token-github=${{secrets.ACTION_TOKEN}}
          - --description=Pre-commit hooks
          - --prettier
          - --python
          - --python-index-name=nanode
          - --python-index-password=lending0safety0email
          - --python-index-url=https://pypi.queensberryresearch.com
          - --python-index-username=qrt
          - --python-package-name-external=qrt-pre-commit-hooks
          - --python-package-name-internal=qrt-pre-commit-hooks
          - --python-version=3.13
          - --repo-name=pre-commit-hooks
          - --shell
          - --toml
        priority: 10
      - id: add-future-import-annotations
        priority: 20
      - id: check-versions-consistent
        priority: 40
      - id: format-pre-commit-config
        priority: 30
      - id: format-pytest
        priority: 30
      - id: format-requirements
        priority: 30
      - id: replace-sequence-str
        priority: 20
      - id: run-prek-autoupdate
        priority: 10
      - id: run-uv-lock
        args:
          - --index-password=lending0safety0email
          - --index-username=qrt
          - --index=https://pypi.queensberryresearch.com/simple
          - --native-tls
        priority: 20
      - id: run-version-bump
        priority: 20
      - id: setup-bump-my-version
        args:
          - --package-name=qrt-pre-commit-hooks
        priority: 20
      - id: setup-ci-pull-request
        args:
          - --certificates
          - --gitea
          - --index-password=${{secrets.NANODE_PYPI_PASSWORD}}
          - --index-username=qrt
          - --index=https://pypi.queensberryresearch.com/simple
          - --pytest-os=ubuntu-latest
          - --pytest-sops-age-key=${{secrets.SOPS_AGE_KEY}}
          - --python-version=3.13
          - --repo-name=pre-commit-hooks
          - --set-up
          - --token-github=${{secrets.ACTION_TOKEN}}
        priority: 20
      - id: setup-ci-push
        args:
          - --certificates
          - --gitea
          - --image
          - --image-namespace=qrt
          - --image-registry-host=gitea.qrt
          - --image-registry-password=${{secrets.QRT_GITEA_READ_WRITE_TOKEN}}
          - --image-registry-port=3000
          - --image-registry-username=qrt-bot
          - --image-runs-on=host-linux
          - --image-uv-index-password=${{secrets.NANODE_PYPI_PASSWORD}}
          - --image-uv-index-username=qrt
          - --image-uv-index=https://pypi.queensberryresearch.com/simple
          - --package
          - --package-password=${{secrets.NANODE_PYPI_PASSWORD}}
          - --package-publish-url=https://pypi.queensberryresearch.com
          - --package-username=qrt
          - --token-github=${{secrets.ACTION_TOKEN}}
        priority: 20
      - id: setup-coverage
        priority: 20
      - id: setup-direnv
        args:
          - --index-name=nanode
          - --index-password=lending0safety0email
          - --index-username=qrt
          - --native-tls
          - --python
          - --version=3.13
        priority: 20
      - id: setup-git
        args:
          - --python
        priority: 20
      - id: setup-pre-commit
        priority: 10
      - id: setup-pyproject
        args:
          - --description=Pre-commit hooks
          - --index-name=nanode
          - --index-url=https://pypi.queensberryresearch.com/simple
          - --name-external=qrt-pre-commit-hooks
          - --name-internal=qrt-pre-commit-hooks
          - --version=3.13
        priority: 20
      - id: setup-pyright
        args:
          - --version=3.13
        priority: 20
      - id: setup-pytest
        args:
          - --package-name=qrt-pre-commit-hooks
        priority: 20
      - id: setup-readme
        args:
          - --description=Pre-commit hooks
          - --repo-name=pre-commit-hooks
        priority: 20
      - id: setup-ruff
        args:
          - --version=3.13
        priority: 20
      - id: update-ci-action-versions
        priority: 20
      - id: update-ci-extensions
        priority: 20
      - id: update-requirements
        args:
          - --index-password=lending0safety0email
          - --index-username=qrt
          - --index=https://pypi.queensberryresearch.com/simple
          - --native-tls
        priority: 20
  - repo: https://github.com/queensberry-research/pre-commit-hooks
    rev: 0.5.17
    hooks:
      - id: add-qrt-hooks
        priority: 10
      - id: modify-ci-push
        args:
          - --index=nanode
        priority: 20
      - id: modify-direnv
        args:
          - --package=infra
        priority: 20
      - id: modify-pre-commit
        args:
          - --ci-image
          - --package=infra
        priority: 10
      - id: modify-pyproject
        args:
          - --package=infra
        priority: 20
      - id: setup-docker
        priority: 20
  - repo: builtin
    hooks:
      - id: check-added-large-files
        priority: 40
      - id: check-case-conflict
        priority: 40
      - id: check-executables-have-shebangs
        priority: 40
      - id: check-json
        priority: 40
      - id: check-json5
        priority: 40
      - id: check-merge-conflict
        priority: 40
      - id: check-symlinks
        priority: 40
      - id: check-toml
        priority: 40
      - id: check-xml
        priority: 40
      - id: check-yaml
        priority: 40
      - id: detect-private-key
        priority: 40
      - id: end-of-file-fixer
        priority: 20
      - id: fix-byte-order-marker
        priority: 20
      - id: mixed-line-ending
        args:
          - --fix=lf
        priority: 20
      - id: no-commit-to-branch
        priority: 40
      - id: trailing-whitespace
        priority: 20
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1
    hooks:
      - id: ruff-check
        args:
          - --fix
        priority: 20
      - id: ruff-format
        priority: 30
  - repo: https://github.com/compwa/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
        args:
          - --option=indent_entries=true
          - --option=indent_tables=true
          - --option=reorder_keys=true
        priority: 30
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
        priority: 40
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-illegal-windows-names
        priority: 40
      - id: destroyed-symlinks
        priority: 40
      - id: pretty-format-json
        args:
          - --autofix
        priority: 20
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
      - id: shfmt
        priority: 30
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npx prettier --write
        language: unsupported
        types_or:
          - markdown
          - yaml
        priority: 30
