[build-system]
  build-backend = "uv_build"
  requires = ["uv_build"]

[dependency-groups]
  dev = [
    "pyright>=1.1.408, <2",
    "rich>=14.2.0, <15",
    "dycw-utilities[test]>=0.181.0, <1",
  ]

[project]
  dependencies = [
    "click>=8.3.1, <9",
    "coloredlogs>=15.0.1, <16",
    "dycw-actions>=0.14.2, <1",
    "dycw-utilities>=0.181.0, <1",
    "rich>=14.2.0, <15",
    "typed-settings[attrs,click]>=25.3.0, <26",
  ]
  description = "Conformalize a repo"
  name = "conformalize"
  readme = "README.md"
  requires-python = ">= 3.13"
  version = "0.2.19"

  [project.scripts]
    conformalize-cli = "conformalize.cli:_main"

[tool]
  [tool.uv]
    [[tool.uv.index]]
      explicit = true
      name = "gitea"
      url = "https://qrt-bot:e43d1df41a3ecf96e4adbaf04e98cfaf094d253e@gitea.main:3000/api/packages/qrt/pypi/simple"
