[build-system]
  build-backend = "uv_build"
  requires = ["uv_build"]

[dependency-groups]
  dev = [
    "pyright>=1.1.408, <2",
    "rich>=14.2.0, <15",
    "dycw-utilities[test]>=0.180.1, <1",
  ]

[project]
  dependencies = [
    "click>=8.3.1, <9",
    "dycw-actions>=0.13.5, <1",
    "dycw-utilities>=0.180.1, <1",
    "rich>=14.2.0, <15",
    "typed-settings[attrs,click]>=25.3.0, <26",
  ]
  description = "Conformalize a repo"
  name = "conformalize"
  readme = "README.md"
  requires-python = ">= 3.13"
  version = "0.2.12"

  [project.scripts]
    conformalize-cli = "conformalize.cli:_main"
