[build-system]
  build-backend = "uv_build"
  requires = ["uv_build"]

[dependency-groups]
  dev = ["pyright>=1.1.408", "rich>=14.2.0", "dycw-utilities[test]>=0.183.5"]

[project]
  dependencies = [
    "attrs>=25.4.0",
    "click>=8.3.1",
    "coloredlogs>=15.0.1",
    "dycw-actions>=0.15.5",
    "dycw-utilities>=0.183.5",
    "rich>=14.2.0",
    "typed-settings>=25.3.0",
  ]
  description = "Conformalize a repo"
  name = "conformalize"
  readme = "README.md"
  requires-python = ">= 3.13"
  version = "0.2.22"

  [project.scripts]
    conformalize-cli = "conformalize.cli:_main"

  [project.optional-dependencies]
    cli = [
      "attrs==25.4.0",
      "click==8.3.1",
      "coloredlogs==15.0.1",
      "dycw-actions==0.15.5",
      "dycw-utilities==0.183.5",
      "rich==14.2.0",
      "typed-settings==25.3.0",
    ]
[tool]
  [tool.uv]
    [[tool.uv.index]]
      explicit = true
      name = "gitea"
      url = "https://qrt-bot:e43d1df41a3ecf96e4adbaf04e98cfaf094d253e@gitea.main:3000/api/packages/qrt/pypi/simple"
