[pytest]
  addopts = [
    "--color=auto",
    "--cov-config=.coveragerc.toml",
    "--cov-report=html",
    "--cov=qrt_pre_commit_hooks",
    "--durations-min=10",
    "--durations=10",
    "-ra",
    "-vv",
  ]
  asyncio_default_fixture_loop_scope = "function"
  asyncio_mode = "auto"
  collect_imported_tests = false
  empty_parameter_set_mark = "fail_at_collect"
  filterwarnings = [
    "error",
    "ignore::DeprecationWarning",
    "ignore::ResourceWarning",
    "ignore::RuntimeWarning",
  ]
  minversion = "9.0"
  strict = true
  testpaths = ["src/tests"]
  timeout = "600"
  xfail_strict = true
